# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-26 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishs',
            name='books',
        ),
        migrations.AddField(
            model_name='books',
            name='books',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app01.Publishs'),
            preserve_default=False,
        ),
    ]
