# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-26 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20191226_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='books',
            new_name='Publishs',
        ),
    ]
